### PR TITLE
Hacky quick upgrade to 0.9.29

### PR DESCRIPTION
**Pull request by apopiak**
Bump versions to 0.9.29 and fix compile issues.
Let me know if you want me to polish it.
Feel free to edit.

### CODE REVIEW

**Comment by shaunxw** [comment]
Thanks for the PR. Can you please fix the CI errors?

**Comment by apopiak** [comment]
> Thanks for the PR. Can you please fix the CI errors?

Seems like the error comes from upstream Substrate. Not sure how to fix that

**Comment by sander2** [comment]
> > Thanks for the PR. Can you please fix the CI errors?
> 
> Seems like the error comes from upstream Substrate. Not sure how to fix that

It's complaining about `bool::then_some` which got [stabilized](https://doc.rust-lang.org/stable/std/primitive.bool.html#method.then_some) only in 1.62. Can one of you upgrade the CI to use a newer compiler version?

**Comment by sander2** [comment]
This PR also needs https://github.com/interlay/xcm-simulator/commit/e4864b9ebfe09fc9aa3919ee72a35c2aa364d7a6 in order for the macros to work

**Review by shaunxw — APPROVED** [review]

**Pull request merged**
